services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag-chatbot-backend
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=${MODEL_NAME:-llama3.2:1b}
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    networks:
      - rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: ./chat
      dockerfile: Dockerfile
    container_name: rag-chatbot-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ollama service (optional - if you want to run Ollama in Docker)
  ollama:
    image: ollama/ollama:latest
    container_name: rag-chatbot-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag-network
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  backend_data:
    driver: local
  ollama_data:
    driver: local

networks:
  rag-network:
    driver: bridge
